# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160808_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='hecho',
            field=models.BooleanField(default=False),
        ),
    ]
